const { addAllEvents } = require("../Data_Model/events.data");
const { addInHouseUsers } = require("../Data_Model/user/inHouseControler.data");
const { connectDB } = require("../utils/mongoDB"); // Ensure MongoDB is initialized properly
require("dotenv").config();

let eventsIDs;

// Events Data
const events = [
  {
    eventID: "Coding",
    eventName: "Coding",
    eventType: "Technical",
    studentCoordinator_1: "Dharshith",
    studentCoordinator_2: "Sahil",
    studentCoordinator_3: "Ankitha",
    studentCoordinator_1PhoneNO: "+91 90372 00857",
    studentCoordinator_2PhoneNO: "+91 87226 58269",
    studentCoordinator_3PhoneNO: "+91 93535 01039",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Ms. Lincy",
    facultyCoordinator_1PhoneNO: "+91 97387 10164",
    img: "https://i.pinimg.com/736x/c9/88/0a/c9880a8abf25f389be7154e8fee18270.jpg",
    descripton: [
      "Teams must consist of only 2 participants.",
      "Any kind of malpractice will lead to direct disqualification.",
      "Participants can use any of the allowed code editors.",
      "Usage of phones during the competition will lead to disqualification.",
      "Teams cannot discuss with other team members during the event.",
      "Languages used: Python, C, and Java.",
    ],
    registrationFee: 200,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Lab 2",
    minimumNoOfParticipants: 1,
    maximumNoOfParticipants: 2,
    amount: 200,
    status: null,
    winners: 2000,
    runners: 1000,
  },
  {
    eventID: "ITManager",
    eventName: "IT Manager",
    eventType: "Technical",
    studentCoordinator_1: "Darshn",
    studentCoordinator_2: "Noufal",
    studentCoordinator_3: "Sanjay",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    studentCoordinator_1PhoneNO: "+91 63668 06447",
    studentCoordinator_2PhoneNO: "+91 93420 59498",
    studentCoordinator_3PhoneNO: "+91 93809 41630",
    facultyCoordinator_1: "Ms. Lincy",
    facultyCoordinator_1PhoneNO: "+91 97387 10164",
    img: "https://www.herzing.edu/sites/default/files/styles/fp_960_480/public/2020-09/how-to-become-it-manager.jpg.webp?itok=lwQyu6da",
    descripton: [
      "The event consists of 3 rounds:",
      "○ Aptitude round, ○ Debate round, ○ Stress Interview round",
      "It is an individual event.",
      "Participation is encouraged from students of all departments.",
      "Participants must adhere strictly to the timing.",
      "Cheating or unethical behaviour will result in immediate disqualification.",
      "The decisions of the judges will be final and binding.",
    ],
    registrationFee: 200,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Mini Auditorium",
    minimumNoOfParticipants: 1,
    maximumNoOfParticipants: 1,
    amount: 200,
    status: null,
    winners: 1000,
    runners: 500,
  },
  {
    eventID: "IT Quiz",
    eventName: "IT Quiz",
    eventType: "Technical",
    studentCoordinator_1: "Govardhan",
    studentCoordinator_2: "Spoorthi",
    studentCoordinator_3: "Sangeetha",
    studentCoordinator_1PhoneNO: "+91 7349015576",
    studentCoordinator_2PhoneNO: "+91 8867373550",
    studentCoordinator_3PhoneNO: "+91 9483851992",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Ms. Lincy",
    facultyCoordinator_1PhoneNO: "+91 97387 10164",
    img: "https://bookends.in/wp-content/uploads/2020/12/IT.jpg",
    descripton: [
      "The event consists of 3 rounds:",
      "(Quiz, Pictogram, Buzzer).",
      "2 participants per team.",
      "Electronic devices will be allowed only for specific rounds.",
      "Participants must adhere strictly to the timing.",
      "Cheating or unethical behavior will lead to immediate disqualification.",
      "Topics include Computer Applications, Programming Languages, AI, Current Computer Trends, and more.",
    ],
    registrationFee: 250,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Room no:107",
    minimumNoOfParticipants: 1,
    maximumNoOfParticipants: 2,
    amount: 250,
    status: null,
    winners: 2000,
    runners: 1000,
  },
  {
    eventID: "Treasure Hunt",
    eventName: "Treasure Hunt",
    eventType: "Technical",
    studentCoordinator_1: "Ajay",
    studentCoordinator_2: "Lavanya",
    studentCoordinator_3: "Kavya",
    studentCoordinator_1PhoneNO: "+91 9448107996",
    studentCoordinator_2PhoneNO: "+91 8050732208",
    studentCoordinator_3PhoneNO: "+91 6363392383",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Ms. Lincy",
    facultyCoordinator_1PhoneNO: "+91 97387 10164",
    img: "https://santoriniparty.com/wp-content/uploads/2015/02/treasuremaplarge3.jpg",
    descripton: [
      "Team of up to 7 members.",
      "No usage of electronic devices.",
      "Remaining rules will be provided on the spot.",
    ],
    registrationFee: 200,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Lawn",
    minimumNoOfParticipants: 4,
    maximumNoOfParticipants: 7,
    amount: 200,
    status: null,
    winners: 3000,
    runners: 1500,
  },
  {
    eventID: "BGMI",
    eventName: "BGMI",
    eventType: "Gaming",
    studentCoordinator_1: "Zayed Pathan",
    studentCoordinator_2: "Suman",
    studentCoordinator_3: "Eshan",
    studentCoordinator_1PhoneNO: "+91 6362675597",
    studentCoordinator_2PhoneNO: "+91 6360362752",
    studentCoordinator_3PhoneNO: "+91 9742078621",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Mr. Suhas",
    facultyCoordinator_1PhoneNO: "+91 9738291164",
    img: "https://www.insidesport.in/wp-content/themes/_isp-v2/assets/src/images/placeholders/bgmi.webp",
    descripton: [
      "Each team must contain 4 players.",
      "Cheating, emulators, or any GFX party apps are strictly prohibited.",
      "If any squad is found using them, they will be disqualified immediately.",
      "Participants must bring their own device and use their own cellular data.",
      "Only mobile phones are allowed; tablets are prohibited.",
      "Only finger gloves are allowed.",
      "Triggers are not allowed.",
    ],
    registrationFee: 250,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Room no:118",
    minimumNoOfParticipants: 3,
    maximumNoOfParticipants: 4,
    amount: 250,
    status: null,
    winners: 3000,
    runners: 1500,
  },
  {
    eventID: "Free Fire",
    eventName: "Free Fire",
    eventType: "Gaming",
    studentCoordinator_1: "Joe",
    studentCoordinator_2: "Vikas",
    studentCoordinator_3: "Charles",
    studentCoordinator_1PhoneNO: "+91 xxxxxxxxxx",
    studentCoordinator_2PhoneNO: "+91 xxxxxxxxxx",
    studentCoordinator_3PhoneNO: "+91 xxxxxxxxxx",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Mr. Suhas",
    facultyCoordinator_1PhoneNO: "+91 9738291164",
    img: "https://dl.dir.freefiremobile.com/common/web_event/hash/54f31449f5f91cf0cc223cc635cd5952jpg",
    descripton: [
      "Players should not stay in one spot for a long time to gain an unfair advantage.",
      "Continuous movement is encouraged.",
      "Gun skins with additional attributes that provide unfair advantages are strictly prohibited.",
      "Characters with special abilities or skills that boost performance are not allowed during the match.",
      "The use of finger sleeves for better grip and faster gameplay is not allowed to maintain equal competition.",
      "Applying powder on hands or the screen to enhance touch sensitivity is strictly forbidden.",
      "The use of any third-party applications, hacks, or modified game files will result in immediate disqualification.",
      "The usage of grenades or throwable explosives is not allowed during the match.",
    ],
    registrationFee: 250,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Room no:209",
    minimumNoOfParticipants: 3,
    maximumNoOfParticipants: 4,
    amount: 250,
    status: null,
    winners: 3000,
    runners: 1500,
  },
  {
    eventID: "NFS",
    eventName: "NFS",
    eventType: "Gaming",
    studentCoordinator_1: "Sudeesh",
    studentCoordinator_2: "Karthikeya",
    studentCoordinator_3: "Sooraj",
    studentCoordinator_1PhoneNO: "+91 9591477641",
    studentCoordinator_2PhoneNO: "+91 8095576370",
    studentCoordinator_3PhoneNO: "+91 6364749843",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Mr. Suhas",
    facultyCoordinator_1PhoneNO: "+91 9738291164",
    img: "https://i.pinimg.com/736x/48/7c/31/487c312cfed8d7a7af62c791728a06e9.jpg",
    descripton: [
      "Participants will be provided devices by the coordinators with keyboard and controller options.",
      "Registration: Players must register individually to participate in the competition.",
      "Rounds: 4 (Might change depending on the number of participants).",
      "Points: Fastest time wins.",
      "Track: The track for the competition will be announced before the competition starts.",
      "Note: Players will be responsible for any damages found on their system, and immediate disqualification will be issued.",
      "Most Wanted 2012.",
    ],
    registrationFee: 100,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Lab 2",
    minimumNoOfParticipants: 1,
    maximumNoOfParticipants: 1,
    amount: 100,
    status: null,
    winners: 1200,
    runners: 800,
  },
  {
    eventID: "Reverse Charades",
    eventName: "Reverse Charades",
    eventType: "Gaming",
    studentCoordinator_1: "Vaishnavi",
    studentCoordinator_2: "Olivia",
    studentCoordinator_3: "Veronica",
    studentCoordinator_1PhoneNO: "+91 8431653151",
    studentCoordinator_2PhoneNO: "+91 8075820081",
    studentCoordinator_3PhoneNO: "+91 9611121400",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Mr. Suhas",
    facultyCoordinator_1PhoneNO: "+91 9738291164",
    img: "https://media.istockphoto.com/id/1701855427/photo/group-of-teenagers-playing-charades-game-at-home.jpg?s=612x612&w=0&k=20&c=ngG6_thwHxfezOCFgaY98Xj9CDVXEZ6DWEwcFKGjoOQ=",
    descripton: [
      'Team: Team must consist of 5 players & 1 player is the "guesser", where the rest of the team acts out the clue and the "guesser" needs to guess the word.',
      "No talking/mouth movements, writing down clues, or pointing towards objects/people. This will lead to direct disqualification.",
      "Scoring: A correct guess earns a point; an incorrect guess earns none.",
      "Turns: Each team gets a specific amount of time in which they have to guess the word. After getting the correct answer or once the time period is over, it will be the next team’s turn.",
    ],
    registrationFee: 300,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Main Auditorium",
    minimumNoOfParticipants: 4,
    maximumNoOfParticipants: 5,
    amount: 300,
    status: null,
    winners: 3000,
    runners: 1500,
  },
  {
    eventID: "Group Singing",
    eventName: "Group Singing",
    eventType: "Cultural",
    studentCoordinator_1: "Sai Chethan",
    studentCoordinator_2: "Saniya",
    studentCoordinator_3: "Roshan",
    studentCoordinator_1PhoneNO: "+91 8088526031",
    studentCoordinator_2PhoneNO: "+91 8310291939",
    studentCoordinator_3PhoneNO: "+91 8105167239",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Ms. Manjula",
    facultyCoordinator_1PhoneNO: "+91 8095379852",
    img: "https://img.freepik.com/free-photo/young-adults-having-fun-open-mic_23-2149501499.jpg",
    descripton: [
      "Each performance is limited to 3+2 minutes, with an extra 2 minutes for stage setup.",
      "Evaluation is based on vocal ability, emotion, and stage presence.",
      "Profanity or vulgarity in performances is not allowed.",
      "Judges' decisions are final and binding.",
      "Any form of singing is allowed.",
      "Team size: 3 to 8 per team.",
    ],
    registrationFee: 500,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Main Auditorium",
    minimumNoOfParticipants: 3,
    maximumNoOfParticipants: 8,
    amount: 500,
    status: null,
    winners: 4000,
    runners: 3000,
  },
  {
    eventID: "Group Dance",
    eventName: "Group Dance",
    eventType: "Cultural",
    studentCoordinator_1: "Ajiqneya",
    studentCoordinator_2: "Raushan",
    studentCoordinator_3: "Sajana",
    studentCoordinator_1PhoneNO: "+91 8971853879",
    studentCoordinator_2PhoneNO: "+91 9591632335",
    studentCoordinator_3PhoneNO: "+91 7907936864",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Ms. Manjula",
    facultyCoordinator_1PhoneNO: "+91 8095379852",
    img: "https://img.freepik.com/free-photo/group-active-kids-cheerful-girls-dancing-isolated-green-background-neon-light_155003-46334.jpg",
    descripton: [
      "Open Theme.",
      "Team: 6-12 Participants.",
      "Time: 4+1 minutes performance. Exceeding time may reduce points.",
      "Simple props are allowed; no flammable, sharp, powder, or water-based items.",
      "Offensive language or misconduct leads to disqualification.",
      "Revealing or inappropriate costumes are strictly prohibited (participants cannot go shirtless on stage).",
      "Teams must report backstage 15-30 minutes before performing.",
      "Judges' decision is final.",
    ],
    registrationFee: 500,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Main Auditorium",
    minimumNoOfParticipants: 6,
    maximumNoOfParticipants: 12,
    amount: 500,
    status: null,
    winners: 5000,
    runners: 2500,
  },
  {
    eventID: "Fashion Show",
    eventName: "Fashion Show",
    eventType: "Cultural",
    studentCoordinator_1: "Alita",
    studentCoordinator_2: "Madiha",
    studentCoordinator_3: "Aman",
    studentCoordinator_1PhoneNO: "+91 7019527086",
    studentCoordinator_2PhoneNO: "+91 8660784342",
    studentCoordinator_3PhoneNO: "+91 9544163226",
    studentCoordinator_Email_IDA: "diagoarden@gmail.com",
    facultyCoordinator_1: "Ms. Manjula",
    facultyCoordinator_1PhoneNO: "+91 8095379852",
    img: "https://www.universityoffashion.com/blog/wp-content/uploads/2019/11/Louis-Vuittons-spring-2020-show.-vogue.jpg",
    descripton: [
      "Each team must have 8 to 12 participants.",
      "The event has no specific theme, allowing teams full creative freedom.",
      "Revealing or inappropriate costumes are strictly prohibited (participants cannot go shirtless on stage).",
      "The time limit is 6+4 minutes; exceeding this will result in negative marking.",
      "Any props must be pre-approved by event coordinators. Fire, water, and hazardous props are strictly banned.",
      "If teams face delays or issues, they should inform the coordinators at least 1 hour before the event starts for assistance.",
      "Disruptive behaviour or misconduct during the event may lead to disqualification.",
      "The judges' decision is final and cannot be challenged.",
    ],
    registrationFee: 600,
    time: "2025-01-27T05:00:00.000Z",
    venue: "Main Auditorium",
    minimumNoOfParticipants: 6,
    maximumNoOfParticipants: 12,
    amount: 600,
    status: null,
    winners: 6000,
    runners: 3000,
  },
];

eventsIDs = events.map((event) => event.eventID.toUpperCase());

// Insert Events & Users
async function startAllProcesses() {
  console.log("Env: ", process.env.NODE_ENV);
  await connectDB();
  // ✅ Fixed eventIDs mapping
  // Create coordinator users from event data
  const coordinatorEmails = events.map((event) => ({
    name: event.studentCoordinator_1,
    emailID: event.studentCoordinator_Email_IDA,
    eventID: event.eventID.toUpperCase(),
  }));

  // Users Data
  const users = [
    { emailID: "diagoarden@gmail.com", userRole: "admin" },
    ...coordinatorEmails,
  ];

  try {
    await addAllEvents(events, eventsIDs);
    await addInHouseUsers(users);
    console.log("All processes completed successfully.");
  } catch (error) {
    console.error("Error in startAllProcesses:", error);
  }
}

// Export
module.exports = { startAllProcesses, eventsIDs };
